modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Apache 2.0"

[[mods]]
modId = "zpl"
version = "${version}"
displayName = "Zero Point Labs"
authors = "G_Mungus, Cosmos, Q"
description = '''
Innovative technologies for high-performance spacecraft locomotion.
'''
logoFile = "assets/zpl/icon.png"

[[dependencies.zpl]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zpl]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zpl]]
modId = "vlib"
mandatory = true
versionRange = "[0.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zpl]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2.4.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zpl]]
modId = "zps"
mandatory = true
versionRange = "[1.3.0,)"
ordering = "NONE"
side = "BOTH"
