modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Apache 2.0"

[[mods]]
modId = "zpl"
version = "${version}"
displayName = "Zero Point Labs"
authors = "G_Mungus"
description = '''
Innovative technologies for high-performance spacecraft locomotion.
'''
logoFile = "assets/zpl/icon.png"

[[dependencies.zpl]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zpl]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
